# this is specific to feature branch 
server:
  port: 8080

spring:
  application:
    name: video-streaming-api
  datasource:
    url: jdbc:postgresql://localhost:5432/video_streaming_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

